### ISSUE TITLE
Sudoku Solver Idea

### ISSUE THREAD

**Issue by miklaskarjalainen** [Thaumatized/sudoku-solver#1]
Vissii käyetään sitten, wavefunction collapsing algoritmia.

https://github.com/mxgmn/WaveFunctionCollapse

:)

**Comment by Thaumatized** [comment]
Tjaa'a kuule. Ei vaikuta oikealta paikalta wave function collapselle. Tulen kyllä varmaan ennemmin tai myöhemmin käyttämään johonkin.
